### PR TITLE
docs: add example on how to configure buildPrefix for serverless-webpack

### PR DESCRIPTION
**Pull request by jaydp17**
I had a hard time figuring this out, thus just trying to make it easier for everyone else 🙂

### CODE REVIEW

**Comment by aheissenberger** [comment]
can you add a note that this is only required if the serverless-webpack is used and that for typescript the value needs to be changed

**Comment by jaydp17** [comment]
@aheissenberger I agree that we need the note that this is only required for `serverless-webpack`.
But why does the value needs to be changed for typescript? I'm using `serverless-webpack` with typescript, and it works

**Comment by aheissenberger** [comment]
my fault - not using typescript :-) just do the changes and I will merge it - thanks for all the small improvements!

**Comment by jaydp17** [comment]
@aheissenberger I've updated that, also given that it was already in the `Using with serverless-offline and serverless-webpack plugin` section, I haven't added a lot more to it
github com_aheissenberger_serverless-appsync-offline_pull_21_files

**Pull request merged**
